### ISSUE TITLE
functional question

### ISSUE THREAD

**Issue by roberto96** [qb60/hikvision-video-downloader#2]
Is it possible to somehow force your program to download all files from the camera, and if the connection is broken, wait for the restoration and then download all the files from the camera. In short, I would like, synchronization of the camera storage with a computer.
Кажется вы говорите на русском, если это так - напишите, есть немного вопросов по коду.
Интересует постоянная выгрузка файлов с хранилища камеры. Камера может быть час в сети, а потом пропасть и еще через час появится. Нужно выгружать все файлы с архива камеры, чтобы программа не останавливала свою работу при обрыве соединения.

**Comment by qb60** [comment]
Конкретно с этой программой такое не получится, нужно или дописывать эту, или писать новую. Например, можно написать отдельный скрипт, который будет следить за файлами в папках камер и с определённой периодичностью запускать эту программу с параметрами времени от последнего загруженного файла до текущего времени.

**Comment by roberto96** [comment]
Можно с вами связаться   для сотрудничества?  Напишите мне в тг или отправьте свои данные, чтобы я мог с вами связаться. tg: iLEV3L

**Comment by roberto96** [comment]
Доброй ночи, ответьте хотя бы, пожалуйста, на вопрос с запросом xml.
![image](https://user-images.githubusercontent.com/29623523/129493152-defce2ae-9964-47d1-8cab-ba6c2949982b.png)

Возвращает мне список файлов, но таких файлов нету в хранилище камеры. Как мне получить именно список файлов с камеры? 
Вот что он мне возвращается при запросе: 
![image](https://user-images.githubusercontent.com/29623523/129493195-53c812f5-44f5-4ab1-974c-cfd0f50920ba.png)

А вот что реально есть, ваша программа их качает без проблем: 
![image](https://user-images.githubusercontent.com/29623523/129493259-c796a970-817c-4fb7-8737-6195ab55dc91.png)

**Comment by qb60** [comment]
Мой скрипт просто сохраняет их с такими именами. В камере они как раз существуют в виде ch01_xxxxxxxxxxxxxxxxx, это можно увидеть, если сохранять записи через веб-интерфейс камеры:
![image](https://user-images.githubusercontent.com/1970596/131068504-5570ca41-ae0f-424d-afcb-f0cab6b5b292.png)
