### ISSUE TITLE
Видео необрезанные 

### ISSUE THREAD

**Issue by kejndan** [qb60/hikvision-video-downloader#3]
Здравствуйте, у проблема с записями, которые скачиваются с видеорегистратора, они не обрезаны. При задание таймкода скачивается огромное видео, в которое попадает данный таймкод, т.е. записи не обрезаются. Это нормально или это как-то можно исправить?

**Comment by qb60** [comment]
Это нормально, файлы создаются камерой/регистратором и скачиваются в таком виде, в котором они там есть. Может быть есть какие-то настройки в самом регистраторе, в камерах ничего такого я не видел.
Можете порезать скачанные записи самостоятельно с помощью ffmpeg, там очень просто это делается.
