### ISSUE TITLE
get time offset DST CST

### ISSUE THREAD

**Issue by surfzoid** [qb60/hikvision-video-downloader#5]
hi
with my NVR  the function to get time offset is broken, just replacing CST by `` isn't enough.
the TIME xml response is :
<Time version="2.0">
<timeMode>platform</timeMode>
<localTime>2022-03-02T17:08:16+01:00</localTime>
<timeZone>
CST-1:00:00DST01:00:00,M3.5.0/02:00:00,M10.5.0/03:00:00
</timeZone>
<platformType>EZVIZ</platformType>
</Time>

is your script want to extract the DST or CST time?

**Comment by surfzoid** [comment]
here it is a solution if you want CST
```
def parse_timezone(raw_timezone):
        #timezone_text = raw_timezone.replace('CST', '')
        timezone_text = raw_timezone[3:11]
        time_offset_parts = timezone_text.split(':')
        hours = int(time_offset_parts[0])
        minutes = int(time_offset_parts[1])
        seconds = int(time_offset_parts[2])
```

**Comment by surfzoid** [comment]
sic
a very lot of time and :
```
Start time: 2022-03-02 00:30:00
End time: 2022-03-02 14:59:59
Getting track list...
Error occurred during getting track list
Error 403 Forbidden: Invalid Operation - methodNotAllowed
Found 0 files
```

**Comment by surfzoid** [comment]
like it is explain here in chapter 8
https://ipvm-uploads.s3.amazonaws.com/uploads/10b4/c3cf/HIKVISION%20ISAPI_2.0-RaCM%20Service.pdf
it is really better to use Post rather Get, now i got file list

**Comment by qb60** [comment]
Hi, @surfzoid . Thank you for you additions, I'll make changes in the repo according to your research.
